In [8]:
import numpy as np
# 1-D Array
arr1=np.arange(1,20)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [17]:
#creating array from the list
elem=[1,2,3,4,5]
print(np.array(elem))
print("With Step size=2 ",np.arange(1,10,2))

[1 2 3 4 5]
With Step size=2  [1 3 5 7 9]


In [27]:
#Arrays of ones and Zeros
print(np.ones(7)) #  creates an array filled with 1
print(np.zeros(7)) # creates an array filled with 0
print(np.full(7,4)) # creates an array of seven elements all filled with 4



[1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0.]
[4 4 4 4 4 4 4]


In [29]:
# Array using Random Numbers
print(np.random.rand(5)) #creates an array of 5 random values
print(np.random.randint(1,10,5)) # takes low, high and number of values

[0.62672327 0.85402082 0.66773718 0.67979568 0.38438   ]
[7 5 8 9 1]


In [ ]:
                                                    Multidimensional  Array

In [33]:
print(np.arange(12).reshape(4,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [39]:
print(np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])) # 2-D array
print(np.array([[[1,2],[2,4],[4,6]]]))

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
[[[1 2]
  [2 4]
  [4 6]]]


In [46]:
print(np.ones(9).reshape(3,3))
print(np.zeros(16).reshape(4,4))
print(np.full(4,2).reshape(2,2))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[2 2]
 [2 2]]


In [ ]:
                                     Array Operations

In [14]:
import numpy as np
a=np.arange(12).reshape(3,4)
b=np.random.randint(20,50,(3,4))
print("Addition",a+b)
print(a-b)
print(a*b)
print(a/b)

Addition [[23 32 25 27]
 [27 29 46 34]
 [31 36 53 56]]
[[-23 -30 -21 -21]
 [-19 -19 -34 -20]
 [-15 -18 -33 -34]]
[[  0  31  46  72]
 [ 92 120 240 189]
 [184 243 430 495]]
[[0.         0.03225806 0.08695652 0.125     ]
 [0.17391304 0.20833333 0.15       0.25925926]
 [0.34782609 0.33333333 0.23255814 0.24444444]]


In [15]:
print(a|b)
print(a&b)
print(a^b)


[[23 31 23 27]
 [23 29 46 31]
 [31 27 43 47]]
[[ 0  1  2  0]
 [ 4  0  0  3]
 [ 0  9 10  9]]
[[23 30 21 27]
 [19 29 46 28]
 [31 18 33 38]]


In [16]:
print(f"Shape: {a.shape},   dim: {a.ndim},  size:{a.size}")

Shape: (3, 4),   dim: 2,  size:12


In [32]:
#Reshaping the array
reshaped=b.reshape(4,3)
print(reshaped)
print(f"Transpose of reshaped:\n {reshaped.T}")

[[23 31 23]
 [24 23 24]
 [40 27 23]
 [27 43 45]]
Transpose of reshaped:
 [[23 24 40 27]
 [31 23 27 43]
 [23 24 23 45]]


In [33]:
# Slicing of array
print(b[2,2])
print(b[1:])
print(b[0,0:2])

23
[[24 23 24]
 [40 27 23]
 [27 43 45]]
[23 31]


In [39]:
print(a,b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[23 31 23]
 [24 23 24]
 [40 27 23]
 [27 43 45]]
